# Local application configuration
server:
  port: 8080

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,refresh
  endpoint:
    health:
      show-details: always

# Application info
info:
  app:
    name: Test Environment Client
    description: Spring Boot client for test environment configuration
    version: 1.0.0
    environment: test

# Logging
logging:
  level:
    com.demo.client.test: INFO
    org.springframework.cloud.config: DEBUG