# Local application configuration
server:
  port: 8090

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,refresh
  endpoint:
    health:
      show-details: always

# Application info
info:
  app:
    name: Development Environment Client
    description: Spring Boot client for development environment configuration
    version: 1.0.0
    environment: dev

# Logging
logging:
  level:
    com.demo.client.dev: INFO
    org.springframework.cloud.config: DEBUG